// //   try-catch

// try{
//     console.log(a+b);}
//     catch(err){
//         console.log(err)
//         console.log("this is error")    
//     }
// console.log("this is still running")

// // throw
// try{
//     throw new ReferenceError();}
//     catch(err){
//         console.log(err)
//         console.log("this is error")    
//     }
// console.log("this is still running");

